on:
  push:
    branches:
      - develop

name: Deploy String boot to Amazon EC2
env:
  PROJECT_NAME: action_codedeploy

jobs:
  deploy:
    name: DEPLOY
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build --args='--app.auth.tokenExpirationMsec=${{ secrets.TOKEN_EXPIRATION }} --app.auth.tokenSecret=${{ secrets.TOKEN_SECRET }} --app.oauth2.authorizedRedirectUris=${{ secrets.AUTHORIZED_REDIRECT_URIS }} --spring.security.oauth2.client.registration.google.clientId=${{ secrets.GOOGLE_CLIENT_ID }} --spring.security.oauth2.client.registration.google.clientSecret=${{ secrets.GOOGLE_CLIENT_SECRET }} --spring.security.oauth2.client.registration.google.redirectUri={{ secrets.GOOGLE_REDIRECT_URI }} --spring.security.oauth2.client.registration.google.scope={{ secrets.GOOGLE_SCOPE }}'
        shell: bash
    
      - name: Zip jar, appspec.yml, deploy.sh files
        working-directory: ./build/libs
        run: |
          mv ../../appspec.yml .
          mv ../../deploy.sh .
          zip moodof.zip *.jar appspec.yml deploy.sh
          rm *.jar *.yml *.sh
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./build/libs/moodof.zip s3://moodof-deploy1/$PROJECT_NAME/moodof.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name moodof-code-deploy --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name dev --s3-location bucket=moodof-deploy1,bundleType=zip,key=$PROJECT_NAME/moodof.zip
